### ISSUE TITLE
支付宝/微信/极光推送不能调起

### ISSUE THREAD

**Issue by symenywong** [weexplus/boilerplate#3]
![image](https://user-images.githubusercontent.com/17674512/51459598-1408d800-1d94-11e9-9432-7117e1ce4b26.png)

**Comment by farwolf2010** [comment]
现在这些模块都作为插件了，需要添加插件，重新打包后，才会有
https://weexplus.github.io/doc/zhi-fu/zhi-fu-bao.html
https://weexplus.github.io/doc/zhi-fu/wei-xin-zhi-fu.html
https://weexplus.github.io/doc/mo-kuai/jpushji-guang-tui-900129.html
